name: eblan_messenger
description: "Eblan-Messenger - Telegram-like messenger"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  dio: ^5.7.0
  socket_io_client: ^3.0.2
  file_picker: ^8.1.6
  image_picker: ^1.1.2
  record: ^5.2.0
  audioplayers: ^6.1.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.4
  intl: ^0.20.2
  path_provider: ^2.1.5
  flutter_local_notifications: ^18.0.1
  record_platform_interface: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
